---
- hosts: localhost
  connection: local
  vars_prompt:
    - name: username
      prompt: Enter your username
      private: false
    - name: password
      prompt: Enter your password
      private: true

  tasks: 
    - name: create user
      become: yes
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
