---
- hosts: localhost
  connection: local
  roles:
    - install
  vars_prompt:
    - name: username
      prompt: Enter your username
      private: false
    - name: password
      prompt: Enter your password
      private: true    
  vars:
    - timezone: America/New_York
