---
- name: Create aur_builder
  become: yes
  user:
    name: aur_builder
    create_home: no
    group: wheel

- name: Add aur_builder to sudoer
  become: yes
  lineinfile:  
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
