---
- name: Install base-devel
  become: yes
  pacman:
    name:
      - fakeroot
      - gcc
      - make

- name: Install CLI
  become: yes
  pacman:
    name:
      - vim
      - tree
      - fzf
      - tldr
      - jq
      - ripgrep
      - httpie

- name: Install terminal
  become: yes
  pacman:
    name:
      - terminator

- name: Install monitoring tools
  become: yes
  pacman:
    name:
      - htop
      - btop
      - hddtemp
      - lm_sensors
      - psensor
