---
- name: Install base-devel
  become: yes
  pacman:
    name:
      - fakeroot
      - gcc
      - make

- name: Install CLI
  become: yes
  pacman:
    name:
      - vim
      - tree
      - fzf
      - tldr
      - jq
      - ripgrep
      - httpie

- name: Install archival tools
  become: yes
  pacman:
    name:
      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar

- name: Install monitoring tools
  become: yes
  pacman:
    name:
      - htop
      - btop
      - hddtemp
      - lm_sensors
      - psensor
      - sysbench

- name: Install stacer
  aur:
    use: yay
    name: stacer

- name: Install hardinfo
  aur:
    use: yay
    name: hardinfo

- name: Install vagrant
  become: yes
  pacman:
    name:
      - vagrant
