---
- name: Install base-devel
  become: yes
  pacman:
    name:
      - fakeroot
      - gcc
      - make

- name: Install yay
  aur:
    name:
      - yay

- name: Install CLI
  become: yes
  pacman:
    name:
      - vim
      - tree
      - fzf
      - tldr
      - jq
      - ripgrep
      - httpie
      - tar
      - unzip

- name: Install monitoring tools
  become: yes
  pacman:
    name:
      - htop
      - btop
      - hddtemp
      - lm_sensors
      - psensor

- name: Install yay
  aur:
    name:
      - yay
