---
- name: Install protobuf
  become: yes
  pacman:
    name: 
      - protobuf
      - meld

- name: Install service test tools
  aur:
    use: yay
    name:
      - postman
      - grpcurl
      #- bloomrpc-bin

- name: Install db tools
  aur: 
    use: yay
    name:
      - dbeaver
      - mysql-workbench
      - tableplus
      - squirrel-sql
      - redis-desktop-manager

- name: Install DataGrip
  flatpak:
    name:
      - datagrip

