---
- name: Install disk utilities
  become: yes
  pacman:
    name:      
      - gparted
      - gnome-disk-utility
      - ncdu
      - baobab
      - smartmontools
      - bleachbit
    state: present

- name: Install timeshift
  aur:
    use: yay
    name: timeshift
