---
- name: Install docker
  become: yes
  pacman:
    state: present
    name:
      - docker
      - docker-compose
    state: present

#- name: Add the user to docker group
#  user: name={{ user.name }} groups=docker append=yes

- name: Enable and start docker socket
  become: yes
  systemd: 
    name: docker.service
    enabled: yes
    state: started
