---
- name: Install Java Tools
  become: yes
  pacman:
    name:
      - jdk11-openjdk
      - openjdk11-src
      - maven
      - gradle
      - intellij-idea-community-edition
    state: present

- name: Install kotlin
  become: yes
  pacman:
    name:      
      - kotlin
    state: present

- name: Install Scala Tools
  become: yes
  pacman:
    name:      
      - scala
      - sbt
    state: present
  
- name: Install Android Studio
  aur:
    use: yay
    name: android-studio
