---
- name: Install system
  import_tasks: system.yml

#- name: Install aur
#  import_tasks: aur.yml

- name: Install yay
  import_tasks: yay.yml

- name: Install base
  import_tasks: base.yml

- name: Install terminal
  import_tasks: terminal.yml

- name: Install software
  import_tasks: software.yml
  
- name: Install network
  import_tasks: network.yml

- name: Install xfce
  import_tasks: xfce.yml

- name: Install zsh
  import_tasks: zsh.yml

- name: Install disk utilities
  import_tasks: disk.yml

- name: Install browser
  import_tasks: browser.yml

- name: Install c_cpp
  import_tasks: c_cpp.yml

- name: Install java dev
  import_tasks: java.yml
