---
- name: Install networkmanager
  become: yes
  pacman:
    name:
      - networkmanager
    state: present

- name: Install openssh
  become: yes
  pacman:
    name:
      - openssh
    state: present

- name: Install utilities
  become: yes
  pacman:
    name:
      - wget
      - curl
      - git
    state: present

- name: Install firewall
  become: yes
  pacman:
    name:
      - gufw
    state: present
