---
- name: Install flatpak
  become: yes
  pacman:
    name: flatpak
    state: present    

#- name: Install snap
#  import_tasks: snap.yml

- name: Install pamac-aur
  aur:
    use: yay
    name: pamac-aur
