---
- name: Install minimal xorg
  become: yes
  pacman:
    name:
      - xorg-server

- name: Install graphic drivers
  become: yes
  pacman:
    name:
      - xf86-video-vesa
      - xf86-video-amdgpu

- name: Install minimal xfce4
  become: yes
  pacman:
    name:
      - xfwm4
      - xfce4-panel
      - xfce4-session
      - xfdesktop
      - thunar

- name: Install selective xfce4
  become: yes
  pacman:
    name:
      - xfce4-appfinder
      - xfce4-power-manager
      - xfce4-terminal
      - xfce4-settings

- name: Install selective xfce4 goodies
  become: yes
  pacman:
    name:
      - mousepad
      - xfce4-artwork
      - xfce4-datetime-plugin
      - xfce4-netload-plugin
      - xfce4-screensaver
      - xfce4-weather-plugin
      - xfce4-whiskermenu-plugin

- name: Install lxdm
  become: yes
  pacman:
    name:
      - lxdm

- name: Enable lxdm
  become: yes
  systemd:
    name: lxdm.service
    enabled: yes      

- name: Install plank
  become: yes
  pacman:
    name:
      - plank

- name: Install Albert
  aur:
    use: yay
    name: albert-bin
