---
- name: Install disk utilities
  become: yes
  pacman:
    name:      
      - gnome-disk-utility
      - ncdu
      - baobab
      - smartmontools
      - bleachbit
    state: present

- name: Enable TRIM for SSD
  become: yes
  systemd: 
    name: fstrim.timer
    enabled: yes
    state: started
