---
- name: Install productivity tools
  become: yes
  pacman:
    name:
      - shotwell
      - peek
      - flameshot
      - libreoffice
      - redshift
      - keepassxc
    state: present

- name: Install pdf reader
  become: yes
  pacman:
    name:
      - okular

#- name: Install PDF
#  flatpak:
#    name:
#      - master-pdf-editor

- name: Install ISO burner
  aur:
    use: yay
    name: etcher-bin
