---
- name: Install productivity tools
  become: yes
  pacman:
    name:
      - shotwell
      - peek
      - flameshot
      - libreoffice
      - redshift
      - keepassxc
    state: present

- name: Install scanner
  become: yes
  pacman:
    name:
      - sane
      - gscan2pdf
      - pdftk
      - simple-scan

- name: Install pdf reader
  become: yes
  pacman:
    name:
      - okular

- name: Install Master PDF
  aur:
    use: yay
    name:
      - masterpdfeditor-free

- name: Install ISO burner
  aur:
    use: yay
    name: etcher-bin
