---
- name: Validate the sudoers file before saving
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL'
    line: '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
