---
- name: Install x2goserver
  become: yes
  pacman:
    name:
      - x2goserver
    state: present

- name: Install x2goclient
  become: yes
  pacman:
    name:
      - x2goclient
    state: present

- name: Enable and start x2goserver.service
  become: yes
  systemd: 
    name: x2goserver.service
    enabled: yes
    #state: started

- name : Enabel X11 forwarding
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    line: '{{item}}'
    state: present
  with_items:
    - 'X11Forwarding yes'
    - 'AllowTcpForwarding yes'
    - 'X11UseLocalhost yes'
    - 'X11DisplayOffset 10'
