---
- name: Uninstall xfce4-terminal
  become: yes
  pacman:
    name:
      - xfce4-terminal
    state: absent

# Choose terminator over xfce4-terminal
- name: Install Terminator
  become: yes
  pacman:
    name:
      - terminator
    state: present

- name: Install plank
  become: yes
  pacman:
    name:
      - plank
    state: present

- name: Install Albert
  aur:
    use: yay
    name: albert-bin
