---
- name: Install vagrant
  become: yes
  pacman:
    name:
      - vagrant
    state: present    

- name: Install protobuf
  become: yes
  pacman:
    name: 
      - protobuf
      - meld
    state: present
