---
- name: Install vagrant
  become: yes
  pacman:
    name:
      - vagrant
    state: present    

- name: Install protobuf
  become: yes
  pacman:
    name: 
      - protobuf
      - meld
    state: present

- name: Install ngrok
  aur:
    use: yay
    name:
      - ngrok

- name: Install service test tools
  aur:
    use: yay
    name:
      - postman
      - grpcurl
      - ngrok
      - bloomrpc-bin

- name: Install db tools
  aur: 
    use: yay
    name:
      - dbeaver
      - mysql-workbench
      - squirrel-sql
      - redis-desktop-manager

#- name: Install DataGrip
#  flatpak:
#    name:
#      - datagrip

- name: Install editors
  become: yes
  pacman:
    name:
      #- bluefish
      #- geany
      - emacs
    state: present

- name: Install editors from aur
  aur:
    use: yay
    name:
      - visual-studio-code-bin
      - sublime-text-4
      - haroopad
