---
- name: Install docker
  become: yes
  pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Add the user to docker group
  become: yes
  user: 
    name: "{{ username }}"
    groups: docker 
    append: yes

- name: Enable and start docker socket
  become: yes
  systemd: 
    name: docker.service
    enabled: yes
    #state: started
