---
- name: Install snapd
  aur:
    use: yay
    name: snapd

- name: Activate snapd.socket
  become: yes
  systemd:
    name: snapd.socket
    enabled: yes
    state: started

- name: Link /snap
  become: yes
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
