---
- name: Ensure locale en_US.UTF-8 locale is present
  become: yes
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set local en_US.UTF-8 locale systemwide
  become: yes
  copy:
    dest: "/etc/locale.conf"
    content: "LANG=en_US.UTF-8"

- name: Set timezone to '{{ timezone }}'
  become: yes
  timezone:
    name: '{{ timezone }}'

- name: Link vi
  become: yes
  file:
    src: "/usr/bin/vim"
    dest: "/usr/bin/vi"
    state: link
